#------------------#Active Profile#------------------spring:  profiles:    active:    - local
---#------------------#Active Group#------------------spring:  profiles:    group:      "dev": "local"---
#------------------
#Local Config
#------------------
server:
  servlet:
    register-default-servlet: true
#Local Logging    
logging:  level:
    root: debug
    
#Local DataSources
spring:  datasource:
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:25432/sampledb
      username: postgres
      password:
      mapper-locations: classpath:/mapper/**/*.xml
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://127.0.0.1:23306/sample
      username: tester
      password: 1q2w3e4r
      mapper-locations: classpath:/mapper/**/*.xml
#Local Profiles   config:    activate:      on-profile:       local
---
#------------------
#Dev Config
#------------------
logging:
  level:
    root: info
spring: 
  config:
    activate:
      on-profile:
       dev       