#------------------#Active Profile#------------------spring:  profiles:    active:    - local
---#------------------#Active Group#------------------spring:  profiles:    group:      "dev": "local"---
#------------------
#Local Config
#------------------
server:
  servlet:
    register-default-servlet: true  port: 9090
#Local Logging    
logging:  pattern:    console: "[%d{HH:mm:ss:SSS}][%-5level][%logger.%method:line%line] - %msg%n"  level:    org:      springframework: DEBUG
    
#Local DataSources
spring:  jpa:    generate-ddl: true    show-sql: true  datasource:    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:25432/postgres
      username: postgres
      password:
      mapper-locations: classpath:/mapper/**/*.xml
    mariadb:
      driver-class-name: org.mariadb.jdbc.Driver
      url: jdbc:mariadb://127.0.0.1:23306/sample
      username: tester
      password: 1q2w3e4r
      mapper-locations: classpath:/mapper/**/*.xml
#Local Profiles   config:    activate:      on-profile:       local
---
#------------------
#Dev Config
#------------------
spring: 
  config:
    activate:
      on-profile:
       dev