#------------------
#Base Config
#------------------
server:
  servlet:
    register-default-servlet: true

#Default Logging    
logging:  level:
    root: debug
    
#Default DataSources
spring:
  datasource:
    postgresql:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:25432/sampledb
      username: postgres
      password:
    mariadb:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:3306/sample
      username: root
      password: 1q2w3e4r
#Default Profiles   config:    activate:      on-profile:       local    use-legacy-processing: true 
#------------------
#Dev Config
#------------------
---
logging:
  level:
    root: debug
spring: 
  config:
    activate:
      on-profile:
       dev